### PR TITLE
Bug fixes and made changes in UI

### LINKED ISSUE #4: Path list doesn't update until page is refreshed
the path list retrieved from database doesn't update when user logout and login or user logout and another user signin

### PR DESCRIPTION
**Pull request by cryogon**
### CHANGELOG

 **UI**
 1. Changed the UI of createPath option
 2. increased the padding of list items
 3. added scrollbar on path list
 4. moved the logout button to dropdown inside username
 5. made the navbar to stick on top

**BUG_FIXES**
 1. Path List is now updating when new path is added on db
 2. fixed latlng not found on start and finish marker of path
 3. Map was zooming too much which leads to error

### CODE REVIEW

File: src/App.vue [hunk 1]
```diff
@@ -18,11 +20,13 @@ export default {
...
     return {
-      username: localStorage.getItem("token"),
+      username: localStorage.getItem("token").toUpperCase(),
     };
   },
   created() {
     this.$store.dispatch("loadToken");
+    this.$store.commit("setCreateMode", false);
+    this.$store.commit("setLocations", []);
   },
```
Comment (blahmonkey) [inline src/App.vue]: @JatinThakur14 Is this needed? I think locations and create mode will have default values when the store is initialized, in their definitions itself

File: src/components/LoginForm.vue [hunk 2]
```diff
@@ -87,7 +104,11 @@ export default {
           this.$store.dispatch("login");
         }
       } catch (err) {
-        alert("Email or Password is wrong");
+        console.log("Catch Section");
+        this.error = true;
```
Comment (blahmonkey) [inline src/components/LoginForm.vue]: @JatinThakur14 Instead of using error and the error msg separately, you can just use the string variable for both.

File: src/components/MapComponent.vue [hunk 3]
```diff
@@ -128,74 +87,32 @@ export default {
...
-    },
-    cancel() {
-      this.pathName = "";
-      this.onCreateMode = false;
-      this.locations = [];
-    },
   },
   created() {
+    this.$store.commit("setMarkerVisibility", false);
+    this.$store.commit("setLocations", []);
```
Comment (blahmonkey) [inline src/components/MapComponent.vue]: @JatinThakur14 Again, these should probably come with default state when the app loads?

**Review by blahmonkey — CHANGES_REQUESTED** [review]

File: src/App.vue [hunk 4]
```diff
@@ -18,11 +20,13 @@ export default {
   name: "MainComponents",
   data() {
     return {
-      username: localStorage.getItem("token"),
+      username: localStorage.getItem("token").toUpperCase(),
```
Comment (blahmonkey) [inline src/App.vue]: @JatinThakur14 If the token isnt there in localstorage, this will throw an error.

**Review by blahmonkey — CHANGES_REQUESTED** [review]

File: src/App.vue (hunk 4 above)
Comment (cryogon) [reply src/App.vue]: It will always be in localStorage, because we can't access the map unless we are logged in. and If we are logged in it will have a token. but I will change it just in case

File: src/App.vue [hunk 5]
```diff
@@ -18,9 +18,12 @@ export default {
   name: "MainComponents",
   data() {
     return {
-      username: localStorage.getItem("token"),
+      username: localStorage.getItem("loginToken") || "",
     };
   },
+  updated() {
+    this.username = localStorage.getItem("loginToken");
```
Comment (blahmonkey) [inline src/App.vue]: @JatinThakur14 Why is `username` = `loginToken` - makes no sense?

File: src/components/LoginForm.vue [hunk 6]
```diff
@@ -55,77 +81,88 @@
...
-import { mapState } from "vuex";
-import router from "@/router";
+import { LOGIN_USER, SIGN_UP } from "@/graphql";
 export default {
   data() {
     return {
       username: "",
       password: "",
       inLoginForm: true,
+      error: false,
```
Comment (blahmonkey) [inline src/components/LoginForm.vue]: @JatinThakur14 you dont need `error` AND `errorText`

File: src/components/LoginForm.vue [hunk 7]
```diff
@@ -55,77 +81,88 @@
...
+      if (this.validated && this.username) {
+        try {
+          this.$apollo.mutate({
+            mutation: SIGN_UP,
+            variables: {
+              username: this.username,
+              password: this.password,
+            },
+          });
+          this.$store.commit("updateToken", this.username);
```
Comment (blahmonkey) [inline src/components/LoginForm.vue]: @JatinThakur14 Same thing. Why is token and username variable being mixed up

**Review by blahmonkey — CHANGES_REQUESTED** [review]

File: src/App.vue (hunk 5 above)
Comment (cryogon) [reply src/App.vue]: Actually I don't have a login token yet so I was using username as loginToken. When the user logs in or sign up his username will be set as loginToken and he will be able use map

File: src/App.vue (hunk 4 above)
Comment (blahmonkey) [reply src/App.vue]: Um this issue is back again

File: src/App.vue [hunk 8]
```diff
@@ -1,81 +1,51 @@
...
-    return {
-      username: localStorage.getItem("token"),
-    };
-  },
   created() {
+    if (!this.$auth0.isAuthenticated) {
+      localStorage.removeItem("apollo-token");
+      return;
+    }
+    console.log(this.$auth0.isAuthenticated);
```
Comment (blahmonkey) [inline src/App.vue]: @JatinThakur14 You can clean up (remove) this console.log

File: src/components/LoginButton.vue [hunk 9]
```diff
@@ -0,0 +1,49 @@
...
+    };
+  },
+
+  methods: {
+    async login() {
+      try {
+        await this.$auth0.loginWithPopup();
+        await this.$nextTick();
+        this.token = await this.$auth0.getAccessTokenSilently();
+        this.token && this.$store.commit("updateToken", this.token);
```
Comment (blahmonkey) [inline src/components/LoginButton.vue]: @JatinThakur14 put these both in an `if` block since you are checking `this.token` two times

**Review by blahmonkey — CHANGES_REQUESTED** [review]

**Review by blahmonkey — APPROVED** [review]
